name: Publish to NPM @beta

on:
  push:
    branches: [beta-release]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - id: publish
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "beta"
      - if: ${{ steps.publish.outputs.type }}
        run: |
          npm version 